[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://fraud-backend.salmonforest-f64ff0e9.uaenorth.azurecontainerapps.io"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
